### ISSUE TITLE
Happy when have same idea 

### ISSUE THREAD

**Issue by chuongmep** [jowsy/bim-net-interactive#1]
Just message with you that  I have same idea before and very interesting with your project : https://github.com/chuongmep/JupyterBIM
My idea before is extend support for Navisworks, Autocad , Revit,... and the interactive not only write code with C#, it also support write with python script.
Can I know your roadmap are working on ? 

Regard !

**Comment by jowsy** [comment]
Amazing ! We think very alike here.
As you say, support for python I also see as an important feature. On the long term, also support for CAD, as you envisioned. I mainly work with Autodesk Revit so it was a natural starting point for me.

For the moment, I am trying to compose a collection of jupyter notebooks in the "samples" folder and test the current implementation. My idea was some kind of Jupyter Book with documentation and showcases. I have made a [get started notebok](https://github.com/jowsy/bim-net-interactive/blob/main/src/GetStarted.ipynb) in the "src"-folder.

Put I feel python-support is really interesting and it would be interesting to explore this possibility in the near future! At the same time, as you probably know, Autodesk are migrating the API to .NET 8 and I am hoping that will solve some dll conflicts. There is a conflict with BIM 360 Addin to mention one.

Cheers!
